name = Omni beta
description = Omni CHI beta layout
preview = preview.png
template = omni_beta-layout

; Regions
regions[notice]			= Notice
regions[user_first]		= First user
regions[user_second]	= Second user
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[lower] 			= Lower
regions[footer]         = Footer
regions[footer_first]	= First footer
regions[footer_second]	= Second footer
regions[footer_third]	= Third footer
regions[footer_fourth]	= Fourth footer
regions[footer_notice]	= Footer notice

; Stylesheets
stylesheets[all][] = css/layouts/omni_beta/omni_beta.layout.css
